### PR TITLE
Update to 1.20.4 and bump version

### PR DESCRIPTION
**Pull request by xTreeTV**
Updated all dependencies for 1.20.4. Bumped version to 1.6.1. In use on my paper build 330 server without issues.

### CODE REVIEW

**Comment by jurohn** [comment]
@xTreeTV Look at #18 its not good!

**Comment by xTreeTV** [comment]
> @xTreeTV Look at #18 its not good!

This fixes #18 which is caused by the former commandapi version being incompatible with 1.20.4. It's not merged with the main repo yet though so you'll have to wait until it is or @MiraculixxT updates it himself and it is released on the website. Or you compile my fork of it yourself.

**Comment by xTreeTV** [comment]
ok looks like it was updated by the dev by now, just not pushed to github yet.

**Comment by MiraculixxT** [comment]
Thanks for updating all dependencies! Even if 1.20.4 paper only needed the version bump for the command-api to work, it's good to update the others too :)

Before publishing 1.20.4 fabric i need to wait for adventure to update

**Pull request merged**
