### PR TITLE
Add support for new Paper Brigadier Command Support

### LINKED ISSUE #26: 1.20.6 error
```
14.05 09:57:57 [Server] ERROR [BlueMap-Marker] Error initializing plugin 'bmm-paper-1.6.4-paper-all.jar' in folder 'plugins' (Is it up to date?)
14.05 09:57:57 [Server] INFO java.lang.NoSuchFieldError: Class net.minecraft.server.MinecraftServer does not have member field 'net.minecraft.commands.Commands vanillaCommandDispatcher'
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.nms.NMS_Common.getBrigadierDispatcher(NMS_Common.java:353) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.CommandAPIBukkit.registerCommandNode(CommandAPIBukkit.java:641) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.CommandAPIHandler.register(CommandAPIHandler.java:664) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.AbstractCommandAPICommand.register(AbstractCommandAPICommand.java:307) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.CommandAPICommand.register(CommandAPICommand.java:60) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.Execution.register(Execution.java:38) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.AbstractCommandTree.register(AbstractCommandTree.java:66) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.CommandTree.register(CommandTree.java:32) ~[?:?]
14.05 09:57:57 [Server] INFO at dev.jorel.commandapi.ExecutableCommand.register(ExecutableCommand.java:236) ~[?:?]
14.05 09:57:57 [Server] INFO at bmm-paper-1.6.4-paper-all.jar/de.miraculixx.bmm.MarkerCommand.<init>(MarkerCommand.kt:449) ~[bmm-paper-1.6.4-paper-all.jar:?]
14.05 09:57:57 [Server] INFO at bmm-paper-1.6.4-paper-all.jar/de.miraculixx.bmm.BMMarker.onLoad(BMMarker.kt:26) ~[bmm-paper-1.6.4-paper-all.jar:?]
14.05 09:57:57 [Server] INFO at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:515) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-78]
14.05 09:57:57 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### PR DESCRIPTION
**Pull request by Zoriot**
For that, changing to the Snapchat Version of CommandAPI was required. Only PaperPlugins support custom Maven Repos. Related to https://github.com/JorelAli/CommandAPI/issues/554. Fixes #26.

### CODE REVIEW

**Comment by Zoriot** [comment]
Maybe its better to just wait for the Release of Command API, but yea here you go. 
[bmm-1_20_6.zip](https://github.com/MiraculixxT/bluemap-marker/files/15366920/bmm-1_20_6.zip)
@MiraculixxT Please review when you have time.

**Comment by MiraculixxT** [comment]
Thanks for the effort! Currently, i would please to give a little bit more time to finish `dev/2.0` which will replace the current version and format

**Comment by Zoriot** [comment]
So can any of my work here be used? Or should I just close it? @MiraculixxT

**Comment by MiraculixxT** [comment]
It is a helpful update for everyone, who want to use the 1.0 version in 1.20.5+. I'll merge it and create a backup branch for everyone interested.
Thanks for the update!

**Pull request merged**
